version: "3"
services:
  nextjs:
    build:
      dockerfile: nextjs.Dockerfile
    container_name: nextjs
    ports:
      - "3000:3000"
    environment:
      INSTAGRAM_ACCESS_TOKEN: ${INSTAGRAM_ACCESS_TOKEN:?err}
